version: "3"

# dotenv:
#   - .env
#   - .env.default

output: prefixed

tasks:
  # |------------------------------------------------------------------------------------------------------------------
  # | Tools
  # |------------------------------------------------------------------------------------------------------------------
  tools:
    desc: Install tools to ./tools directory
    deps:
      - tools:go-licenses
      - tools:golangci-lint
      - tools:rancher-machine
    silent: true
    cmd: >
      echo "✅ ALL TOOLS INSTALLED"

  tools:go-licenses:
    run: once
    vars:
      VERSION: v1.6.0
    cmd: >
      mkdir -p ./tools
      && export GOBIN="$(realpath ./tools)"
      && go install github.com/google/go-licenses@{{.VERSION}}

  tools:golangci-lint:
    run: once
    vars:
      VERSION: v1.64.6
    status:
      - >
        ./tools/golangci-lint version --format short
        | grep -q '{{.VERSION}}'
    cmd: >
      mkdir -p ./tools
      && export GOBIN="$(realpath ./tools)"
      && go install github.com/golangci/golangci-lint/cmd/golangci-lint@{{.VERSION}}

  tools:rancher-machine:
    run: once
    vars:
      VERSION: v0.15.0-rancher126
    status:
      - >
        ./tools/rancher-machine --version
        | grep -q '{{.VERSION}}'
    cmd: >
      mkdir -p ./tools
      && curl -L https://github.com/rancher/machine/releases/download/{{.VERSION}}/rancher-machine-amd64.tar.gz
      | tar -xvzf - -C ./tools

  # |------------------------------------------------------------------------------------------------------------------
  # | Dependencies
  # |------------------------------------------------------------------------------------------------------------------
  dependencies:
    desc: Install dependencies
    deps:
      - dependencies:go
      - dependencies:node
    silent: true
    cmd: >
      echo "✅ ALL DEPENDENCIES INSTALLED"

  dependencies:go:
    run: once
    method: checksum
    sources:
      - go.mod
      - go.sum
    cmds:
      - go mod tidy
      - go mod vendor

  dependencies:node:
    run: once
    method: checksum
    sources:
      - package.json
      - yarn.lock
    cmd: >
      yarn install --frozen-lockfile

  # |------------------------------------------------------------------------------------------------------------------
  # | License checks
  # |------------------------------------------------------------------------------------------------------------------
  licenses:
    desc: Check licenses
    deps:
      - licenses:go
      - licenses:node
    silent: true
    cmd: >
      echo "✅ ALL LICENSES VALID"

  licenses:save:
    desc: Save third-party licenses to licenses.txt
    deps:
      - dependencies:go
      - dependencies:node
      - tools:go-licenses
    cmd: ./tasks/licenses-save.sh

  licenses:go:
    run: once
    deps:
      - tools:go-licenses
      - dependencies:go
    cmd: ./tasks/licenses-go.sh

  licenses:node:
    run: once
    deps:
      - dependencies:node
    cmd: ./tasks/licenses-node.sh

  # |------------------------------------------------------------------------------------------------------------------
  # | Linters
  # |------------------------------------------------------------------------------------------------------------------
  lint:
    desc: Run linters
    deps:
      - lint:commits
      - lint:go
      - lint:node
      - lint:markdown
    silent: true
    cmd: >
      echo "✅ ALL LINTERS PASSED"

  lint:commits:
    run: once
    deps:
      - dependencies:node
    cmd: >
      yarn exec commitlint -- --from=main --verbose

  lint:go:
    run: once
    deps:
      - tools:golangci-lint
      - dependencies:go
    cmd: >
      ./tools/golangci-lint run -v

  lint:node:
    run: once
    deps:
      - dependencies:node
    cmd: >
      yarn exec eslint

  lint:markdown:
    run: once
    deps:
      - dependencies:node
    cmd: >
      yarn exec markdownlint-cli2 -- '**/*.md' '!vendor/**' '!node_modules/**'

  # |------------------------------------------------------------------------------------------------------------------
  # | Builds
  # |------------------------------------------------------------------------------------------------------------------
  build:
    desc: Build project
    deps:
      - build:docker-machine-driver-jrytio-pve
      - build:jrytio-jrytio-pve-node-driver
    silent: true
    cmd: >
      echo "✅ PROJECT BUILT"

  build:docker-machine-driver-jrytio-pve:
    run: once
    deps:
      - dependencies:go
    sources:
      - cmd/**/*.go
    cmd: >
      mkdir -p ./bin
      && CGO_ENABLED="0" go build -o ./bin/docker-machine-driver-jrytio-pve ./cmd/docker-machine-driver-jrytio-pve

  build:jrytio-jrytio-pve-node-driver:
    run: once
    deps:
      - dependencies:node
    sources:
      - pkd/**/*
    cmd: >
      yarn build-pkg jrytio-pve-node-driver
